import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsEn: SkillDetailMap = {
  brainstorm: {
    title: 'Brainstorm',
    command: '/hapo:brainstorm',
    category: 'Discovery',
    summary: 'Scout-first ideation before a spec exists. It turns raw intent into spec-ready decisions without writing implementation code.',
    when: ['The request is vague or broad.', 'Architecture choices are still open.', 'You need scope gates, risks, or tradeoffs before committing to a spec.'],
    flow: [['Scout', 'Inspect the repo or relevant context first.'], ['Frame', 'Name the problem, user value, constraints, non-goals, and risks.'], ['Compare', 'Evaluate simple architecture options and tradeoffs.'], ['Decide', 'Produce spec-ready decisions and open questions.'], ['Handoff', 'Move to specs only after the direction is clear.']],
    output: 'A focused product and architecture direction ready for `/hapo:specs`.',
    avoid: 'Do not use it to write code, create scaffolds, or mark implementation choices as final without approval.',
    next: '/hapo:specs',
  },
  specs: {
    title: 'Specs',
    command: '/hapo:specs',
    category: 'Specification',
    summary: 'Creates the durable feature contract: requirements, research, design, task packets, and validation state.',
    when: ['The direction is clear enough to become requirements.', 'You need task files before coding.', 'The feature needs traceable scope and evidence gates.'],
    flow: [['Detect', 'Check incomplete specs and avoid duplicates.'], ['Requirements', 'Write behavior, constraints, and acceptance criteria.'], ['Research', 'Record source-backed findings and decisions.'], ['Design', 'Define architecture, contracts, data flow, and invariants.'], ['Tasks', 'Split work into task packets with evidence criteria.'], ['Validate', 'Check spec.json, task files, and registry alignment.']],
    output: 'A `specs/<feature>/` directory ready for task-by-task implementation.',
    avoid: 'Do not use specs as decoration after code is already guessed. The spec should constrain implementation.',
    next: '/hapo:develop',
  },
  develop: {
    title: 'Develop',
    command: '/hapo:develop',
    category: 'Implementation',
    summary: 'Implements approved task packets with scope fidelity, task-aware inspection, verification, review, and state sync.',
    when: ['A spec or task packet is approved.', 'You want one task implemented safely.', 'The task has completion criteria and evidence expectations.'],
    flow: [['Load', 'Open spec.json and select one unblocked task.'], ['Extract', 'Read scope, related files, requirements, contracts, and evidence commands.'], ['Inspect', 'Scout real entrypoints, callers, patterns, prior outputs, and blast radius.'], ['Implement', 'Change only the active task boundary unless a justified scope escape is required.'], ['Gate', 'Run tests and review; failures route back to implementation.'], ['Sync', 'Close the task only after proof exists.']],
    output: 'Reachable production code plus task evidence and synchronized state.',
    avoid: 'Do not use it before spec approval or to silently replace named technologies with placeholders.',
    next: '/hapo:test and /hapo:code-review',
  },
  test: {
    title: 'Test',
    command: '/hapo:test',
    category: 'Verification',
    summary: 'Runs real verification and returns a concrete verdict instead of treating green-looking commands as proof.',
    when: ['Implementation changed behavior.', 'You need blast-radius, full-suite, spec-aware, or UI verification.', 'A task needs evidence before it can be done.'],
    flow: [['Detect', 'Find test runner and relevant commands.'], ['Scope', 'Choose blast-radius, full-suite, spec-aware, or UI mode.'], ['Execute', 'Run real lint, type, build, test, or UI checks.'], ['Compare', 'Match results to requirements, design contracts, evidence, and reachability.'], ['Verdict', 'Return PASS, FAIL, PARTIAL, or NO_TESTS with next action.']],
    output: 'A test verdict with commands, outcomes, failures, coverage, and reachability notes when relevant.',
    avoid: 'Never treat NO_TESTS, skipped tests, weakened assertions, or zero executed tests as pass.',
    next: '/hapo:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/hapo:code-review',
    category: 'Review',
    summary: 'Findings-first review for spec compliance, code quality, security, regressions, and contract drift.',
    when: ['A diff is ready for review.', 'You need an adversarial pass before marking work done.', 'A PR, commit, path, or feature scope needs risk analysis.'],
    flow: [['Target', 'Load pending diff, commit, PR, path, or feature scope.'], ['Spec compliance', 'Check missing requirements, extras, wrong runtime choices, and unverified claims.'], ['Code quality', 'Review YAGNI, KISS, DRY, boundaries, naming, and tests.'], ['Adversarial pass', 'Look for security holes, races, edge cases, and regressions.'], ['Score', 'Return pass/fail with severity-ordered findings.']],
    output: 'A blocking review report. Critical findings prevent completion.',
    avoid: 'Do not use it as a summary-only polish step. It should try to break the change.',
    next: '/hapo:sync after fixes and clean verification',
  },
  sync: {
    title: 'Sync',
    command: '/hapo:sync',
    category: 'State',
    summary: 'Keeps machine state and human task files aligned so future agents can trust the project record.',
    when: ['Task status needs to change.', 'spec.json and task markdown drifted.', 'You need an audit of task registry and physical task files.'],
    flow: [['Resolve', 'Identify feature, task, target status, and blocker if any.'], ['Machine state', 'Update spec.json task_registry precisely.'], ['Human state', 'Update task markdown status and checked criteria.'], ['Proof gate', 'Reject done without a verification receipt.'], ['Audit', 'Repair mismatches across task_files, registry, and task files.']],
    output: 'Synchronized spec.json and task markdown with proof-backed status.',
    avoid: 'Do not mark done from chat memory or without evidence in the task file.',
    next: 'Docs checkpoint or next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/hapo:debug',
    category: 'Diagnosis',
    summary: 'Diagnostic-only root-cause workflow for bugs, failing tests, CI issues, performance issues, and UI regressions.',
    when: ['Root cause is unknown.', 'A test, build, CI job, UI flow, or production behavior fails.', 'You need evidence before changing code.'],
    flow: [['Scout', 'Map affected files, callers, runtime, config, tests, and recent changes.'], ['Evidence', 'Capture exact symptom, command, logs, stack trace, and environment facts.'], ['Patterns', 'Compare failing path with nearby working examples.'], ['Hypotheses', 'Test competing causes one variable at a time.'], ['Root cause', 'Trace file/line or config source and explain why now.'], ['Plan', 'Define blast radius and verification checks for the fix.']],
    output: 'A root-cause contract ready for `/hapo:hotfix` or implementation work.',
    avoid: 'Do not edit product code while diagnosing except temporary instrumentation that is removed before handoff.',
    next: '/hapo:hotfix',
  },
  hotfix: {
    title: 'Hotfix',
    command: '/hapo:hotfix',
    category: 'Repair',
    summary: 'Narrow, evidence-backed repair after diagnosis. It fixes the cause without expanding scope.',
    when: ['A root cause has been identified.', 'The fix should be small and safe.', 'A production bug needs targeted regression checks.'],
    flow: [['Evidence', 'Start from a completed debug contract or diagnose first.'], ['Scope', 'Limit the file set to the confirmed cause.'], ['Fix', 'Apply the real repair, not a symptom mask.'], ['Verify', 'Re-run reproduction and targeted regression checks.'], ['Report', 'State cause, fix, evidence, residual risk, and follow-up.']],
    output: 'A focused repair with before/after proof.',
    avoid: 'Do not use it for broad redesigns, speculative refactors, or feature work.',
    next: '/hapo:test and /hapo:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/hapo:docs',
    category: 'Documentation',
    summary: 'Creates, refreshes, summarizes, or reconstructs project documentation from source code.',
    when: ['Docs are missing or stale.', 'A code change affects architecture, commands, deployment, or onboarding.', 'A legacy system needs source-backed as-is documentation.'],
    flow: [['Mode', 'Choose init, update, summarize, or reconstruct.'], ['Scout', 'Read source, config, commands, architecture, and docs root.'], ['Write', 'Update living docs or build docs/as-is for a bounded scope.'], ['Uncertainty', 'Track assumptions, unknowns, and evidence.'], ['Validate', 'Run docs validators before handoff.']],
    output: 'Documentation grounded in current source behavior.',
    avoid: 'Do not invent architecture claims that cannot be backed by files, commands, or runtime evidence.',
    next: '/hapo:specs for modernization work, or release handoff',
  },
  inspect: {
    title: 'Inspect',
    command: '/hapo:inspect',
    category: 'Discovery',
    summary: 'Fast codebase discovery for file finding, task context, entrypoints, call paths, and blast radius.',
    when: ['Relevant files are unclear.', 'A task spans multiple directories.', 'Debugging, implementation, or review needs scoped context.'],
    flow: [['Scope gate', 'Avoid root-wide scans and no-scan paths.'], ['Structure scout', 'Map the top-level layout for broad scopes.'], ['Explore', 'Search focused sub-scopes in parallel or with targeted reads.'], ['Aggregate', 'Return files, call paths, integration points, risks, and next steps.']],
    output: 'A compact context map for safer follow-up work.',
    avoid: 'Do not scan secrets, build outputs, node_modules, .git, or the entire repo when a bounded scope is enough.',
    next: 'The smallest skill that fits the discovered task',
  },
  git: {
    title: 'Git',
    command: '/hapo:git',
    category: 'Release',
    summary: 'Safe branch, commit, push, PR, finish, and worktree operations with secret scanning and focused commits.',
    when: ['Verified changes are ready to commit or publish.', 'You need a focused conventional commit.', 'Parallel work needs an isolated worktree.'],
    flow: [['Status', 'Inspect branch, staged diff, unstaged diff, and intended action.'], ['Secret scan', 'Refuse commits containing keys, tokens, passwords, or credentials.'], ['Split', 'Keep commits focused and conventional when needed.'], ['Publish', 'Commit, push, or open PR safely.'], ['Finish', 'Offer merge, PR, keep, or discard choices after verification.']],
    output: 'Clean version-control history without leaking secrets or overwriting unrelated work.',
    avoid: 'Do not force-push, delete worktrees, or discard changes without explicit user confirmation.',
    next: 'Push, PR, or branch finish flow',
  },
};
