import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsJa: SkillDetailMap = {
  brainstorm: {
    title: 'Brainstorm',
    command: '/hapo:brainstorm',
    category: 'Discovery',
    summary: 'Spec が存在する前の scout-first ideation です。raw intent を implementation code ではなく spec-ready decisions に変えます。',
    when: ['Request が曖昧または広すぎる。', 'Architecture choices がまだ開いている。', 'Spec に入る前に scope gates、risks、tradeoffs が必要。'],
    flow: [['Scout', 'Repo または relevant context を先に inspect します。'], ['Frame', 'Problem、user value、constraints、non-goals、risks を定義します。'], ['Compare', '単純な architecture options と tradeoffs を比較します。'], ['Decide', 'Spec-ready decisions と open questions を出します。'], ['Handoff', '方向が明確になってから specs に進みます。']],
    output: '`/hapo:specs` に渡せる focused product and architecture direction。',
    avoid: 'Code、scaffold、未承認の implementation choice を作るためには使いません。',
    next: '/hapo:specs',
  },
  specs: {
    title: 'Specs',
    command: '/hapo:specs',
    category: 'Specification',
    summary: 'Durable feature contract を作ります: requirements、research、design、task packets、validation state。',
    when: ['Direction が requirements に変換できるほど明確。', 'Coding の前に task files が必要。', 'Feature に traceable scope と evidence gates が必要。'],
    flow: [['Detect', 'Incomplete specs を確認し duplicate を避けます。'], ['Requirements', 'Behavior、constraints、acceptance criteria を書きます。'], ['Research', 'Source-backed findings と decisions を記録します。'], ['Design', 'Architecture、contracts、data flow、invariants を定義します。'], ['Tasks', 'Work を evidence criteria 付き task packets に分割します。'], ['Validate', 'spec.json、task files、registry alignment を確認します。']],
    output: 'Task-by-task implementation に進める `specs/<feature>/` directory。',
    avoid: 'Code を推測した後の飾りとして spec を作りません。Spec は implementation を制約するものです。',
    next: '/hapo:develop',
  },
  develop: {
    title: 'Develop',
    command: '/hapo:develop',
    category: 'Implementation',
    summary: 'Approved task packets を scope fidelity、task-aware inspection、verification、review、state sync とともに実装します。',
    when: ['Spec または task packet が approve 済み。', '1 task を安全に実装したい。', 'Task に completion criteria と evidence expectations がある。'],
    flow: [['Load', 'spec.json を開き、1つの unblocked task を選びます。'], ['Extract', 'Scope、related files、requirements、contracts、evidence commands を読みます。'], ['Inspect', 'Real entrypoints、callers、patterns、prior outputs、blast radius を scout します。'], ['Implement', 'Justified scope escape 以外は active task boundary だけ変更します。'], ['Gate', 'Tests と review を実行し、fail なら implementation に戻ります。'], ['Sync', 'Proof が存在してから task を close します。']],
    output: 'Reachable production code、task evidence、synchronized state。',
    avoid: 'Spec approval 前、または named technologies を placeholder に置き換えるためには使いません。',
    next: '/hapo:test and /hapo:code-review',
  },
  test: {
    title: 'Test',
    command: '/hapo:test',
    category: 'Verification',
    summary: 'Real verification を実行し、green-looking command を proof と誤認せず concrete verdict を返します。',
    when: ['Implementation が behavior を変更した。', 'Blast-radius、full-suite、spec-aware、UI verification が必要。', 'Task が done になる前に evidence が必要。'],
    flow: [['Detect', 'Test runner と relevant commands を見つけます。'], ['Scope', 'blast-radius、full-suite、spec-aware、UI mode を選びます。'], ['Execute', 'Real lint、type、build、test、UI checks を実行します。'], ['Compare', 'Results を requirements、design contracts、evidence、reachability と比較します。'], ['Verdict', 'PASS、FAIL、PARTIAL、NO_TESTS と next action を返します。']],
    output: 'Commands、outcomes、failures、coverage、必要なら reachability notes を含む test verdict。',
    avoid: 'NO_TESTS、skipped tests、弱めた assertions、zero executed tests を pass と扱いません。',
    next: '/hapo:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/hapo:code-review',
    category: 'Review',
    summary: 'Spec compliance、code quality、security、regressions、contract drift を見る findings-first review。',
    when: ['Diff が review ready。', 'Done にする前に adversarial pass が必要。', 'PR、commit、path、feature scope に risk analysis が必要。'],
    flow: [['Target', 'Pending diff、commit、PR、path、feature scope を load します。'], ['Spec compliance', 'Missing requirements、extras、wrong runtime choices、unverified claims を確認します。'], ['Code quality', 'YAGNI、KISS、DRY、boundaries、naming、tests を review します。'], ['Adversarial pass', 'Security holes、races、edge cases、regressions を探します。'], ['Score', 'Severity 順 findings と pass/fail を返します。']],
    output: 'Blocking review report。Critical findings は completion を止めます。',
    avoid: 'Summary-only polish step として使いません。Change を壊しにいく review です。',
    next: 'Clean verification 後に /hapo:sync',
  },
  sync: {
    title: 'Sync',
    command: '/hapo:sync',
    category: 'State',
    summary: 'Machine state と human task files を同期し、future agents が project record を信頼できるようにします。',
    when: ['Task status を変更する必要がある。', 'spec.json と task markdown が drift している。', 'Task registry と physical task files の audit が必要。'],
    flow: [['Resolve', 'Feature、task、target status、blocker を特定します。'], ['Machine state', 'spec.json task_registry を正確に更新します。'], ['Human state', 'Task markdown status と checked criteria を更新します。'], ['Proof gate', 'Verification receipt なしの done を拒否します。'], ['Audit', 'task_files、registry、task files の mismatch を修復します。']],
    output: 'Proof-backed status を持つ synchronized spec.json and task markdown。',
    avoid: 'Chat memory だけ、または task file に evidence がない状態で done にしません。',
    next: 'Docs checkpoint または next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/hapo:debug',
    category: 'Diagnosis',
    summary: 'Bugs、failing tests、CI issues、performance issues、UI regressions のための diagnostic-only workflow。',
    when: ['Root cause が不明。', 'Test、build、CI job、UI flow、production behavior が fail している。', 'Code change 前に evidence が必要。'],
    flow: [['Scout', 'Affected files、callers、runtime、config、tests、recent changes を map します。'], ['Evidence', 'Exact symptom、command、logs、stack trace、environment facts を capture します。'], ['Patterns', 'Failing path と nearby working examples を比較します。'], ['Hypotheses', '複数の cause を 1 variable at a time で検証します。'], ['Root cause', 'File/line または config source と why now を trace します。'], ['Plan', 'Fix の blast radius と verification checks を定義します。']],
    output: '`/hapo:hotfix` または implementation work に渡せる root-cause contract。',
    avoid: 'Diagnosis 中に product code を修正しません。Temporary instrumentation は handoff 前に remove します。',
    next: '/hapo:hotfix',
  },
  hotfix: {
    title: 'Hotfix',
    command: '/hapo:hotfix',
    category: 'Repair',
    summary: 'Diagnosis 後の narrow, evidence-backed repair。Scope を広げず cause を修正します。',
    when: ['Root cause が特定済み。', 'Fix は small and safe であるべき。', 'Production bug に targeted regression checks が必要。'],
    flow: [['Evidence', 'Completed debug contract から始めるか、先に diagnose します。'], ['Scope', 'Confirmed cause に必要な file set に限定します。'], ['Fix', 'Symptom mask ではなく real repair を適用します。'], ['Verify', 'Reproduction と targeted regression checks を再実行します。'], ['Report', 'Cause、fix、evidence、residual risk、follow-up を報告します。']],
    output: 'Before/after proof を持つ focused repair。',
    avoid: 'Broad redesign、speculative refactor、feature work には使いません。',
    next: '/hapo:test and /hapo:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/hapo:docs',
    category: 'Documentation',
    summary: 'Source code から project documentation を create、refresh、summarize、reconstruct します。',
    when: ['Docs が missing または stale。', 'Code change が architecture、commands、deployment、onboarding に影響する。', 'Legacy system に source-backed as-is documentation が必要。'],
    flow: [['Mode', 'init、update、summarize、reconstruct を選びます。'], ['Scout', 'Source、config、commands、architecture、docs root を読みます。'], ['Write', 'Living docs を update、または bounded scope の docs/as-is を作ります。'], ['Uncertainty', 'Assumptions、unknowns、evidence を track します。'], ['Validate', 'Handoff 前に docs validators を実行します。']],
    output: 'Current source behavior に grounded な documentation。',
    avoid: 'Files、commands、runtime evidence で back できない architecture claims を作りません。',
    next: 'Modernization work は /hapo:specs、または release handoff',
  },
  inspect: {
    title: 'Inspect',
    command: '/hapo:inspect',
    category: 'Discovery',
    summary: 'File finding、task context、entrypoints、call paths、blast radius のための fast codebase discovery。',
    when: ['Relevant files が不明。', 'Task が複数 directories にまたがる。', 'Debugging、implementation、review に scoped context が必要。'],
    flow: [['Scope gate', 'Root-wide scans と no-scan paths を避けます。'], ['Structure scout', 'Broad scopes では top-level layout を map します。'], ['Explore', 'Focused sub-scopes を parallel search または targeted reads で調査します。'], ['Aggregate', 'Files、call paths、integration points、risks、next steps を返します。']],
    output: 'Follow-up work を安全にする compact context map。',
    avoid: 'Secrets、build outputs、node_modules、.git、または bounded scope で足りるのに entire repo を scan しません。',
    next: 'Discovered task に合う smallest skill',
  },
  git: {
    title: 'Git',
    command: '/hapo:git',
    category: 'Release',
    summary: 'Secret scanning と focused commits を含む safe branch、commit、push、PR、finish、worktree operations。',
    when: ['Verified changes を commit または publish できる。', 'Focused conventional commit が必要。', 'Parallel work に isolated worktree が必要。'],
    flow: [['Status', 'Branch、staged diff、unstaged diff、intended action を確認します。'], ['Secret scan', 'Keys、tokens、passwords、credentials を含む commit を拒否します。'], ['Split', '必要なら commit を focused and conventional に保ちます。'], ['Publish', 'Commit、push、PR を安全に行います。'], ['Finish', 'Verification 後に merge、PR、keep、discard choices を出します。']],
    output: 'Secrets を漏らさず unrelated work を壊さない clean version-control history。',
    avoid: 'Explicit confirmation なしに force-push、delete worktrees、discard changes をしません。',
    next: 'Push、PR、または branch finish flow',
  },
};
