import { SkillDetailMap } from './skill-detail-types';

export const skillDetailsVi: SkillDetailMap = {
  question: {
    title: 'Question',
    command: '/hapo:question',
    category: 'Consultation',
    summary: 'Skill hỏi đáp có evidence cho source code, docs, specs, config, dependencies, workflow, và thông tin kỹ thuật bên ngoài.',
    when: ['Cần hiểu một luồng hoặc hành vi trong hệ thống hiện tại.', 'Cần câu trả lời có bằng chứng trước khi plan hoặc sửa code.', 'Source trong repo có thể chưa đủ và cần đối chiếu docs/internet hiện tại.'],
    flow: [['Classify', 'Xác định câu hỏi thuộc code behavior, config, specs, dependencies, workflow, hay external knowledge.'], ['Scout', 'Đọc README, docs, specs, code, config, tests, và package metadata trước khi kết luận.'], ['Research', 'Chỉ dùng external/current sources khi repo thiếu bằng chứng hoặc topic phụ thuộc version.'], ['Answer', 'Tách facts đã confirm từ source với inference và cite evidence.'], ['Ask back', 'Chỉ hỏi lại 1 câu tập trung khi nếu trả lời ngay sẽ dễ sai.']],
    output: 'Câu trả lời trực tiếp kèm evidence, confidence, gaps, và next step khi cần.',
    avoid: 'Không implement, scaffold, sửa product code, tạo spec, hoặc xem inference như fact đã confirm.',
    next: '/hapo:brainstorm, /hapo:specs, /hapo:docs, hoặc /hapo:debug tùy kết quả trả lời',
  },
  brainstorm: {
    title: 'Brainstorm',
    command: '/hapo:brainstorm',
    category: 'Discovery',
    summary: 'Ideation scout-first trước khi có spec. Skill này biến intent thô thành quyết định đủ sẵn sàng cho spec mà không viết code implementation.',
    when: ['Request còn mơ hồ hoặc quá rộng.', 'Architecture choice vẫn đang mở.', 'Cần scope gate, risk, hoặc tradeoff trước khi commit vào spec.'],
    flow: [['Scout', 'Inspect repo hoặc context liên quan trước.'], ['Frame', 'Gọi tên problem, user value, constraints, non-goals, và risks.'], ['Compare', 'So sánh architecture options đơn giản và tradeoffs.'], ['Decide', 'Tạo decisions đủ sẵn sàng cho spec và open questions.'], ['Handoff', 'Chỉ chuyển sang specs khi hướng đã rõ.']],
    output: 'Hướng product và architecture tập trung, sẵn sàng cho `/hapo:specs`.',
    avoid: 'Không dùng để viết code, scaffold, hoặc chốt implementation choice khi chưa approve.',
    next: '/hapo:specs',
  },
  specs: {
    title: 'Specs',
    command: '/hapo:specs',
    category: 'Specification',
    summary: 'Tạo feature contract bền vững: requirements, research, design, task packets, và validation state.',
    when: ['Hướng đã đủ rõ để thành requirements.', 'Cần task files trước khi code.', 'Feature cần traceable scope và evidence gates.'],
    flow: [['Detect', 'Kiểm tra spec đang dở và tránh duplicate.'], ['Requirements', 'Viết behavior, constraints, và acceptance criteria.'], ['Research', 'Ghi findings và decisions có source backing.'], ['Design', 'Định nghĩa architecture, contracts, data flow, invariants.'], ['Tasks', 'Tách work thành task packets có evidence criteria.'], ['Validate', 'Kiểm tra spec.json, task files, và registry alignment.']],
    output: 'Thư mục `specs/<feature>/` sẵn sàng để implement từng task một.',
    avoid: 'Không dùng spec như tài liệu trang trí sau khi code đã đoán xong. Spec phải constrain implementation.',
    next: '/hapo:develop',
  },
  develop: {
    title: 'Develop',
    command: '/hapo:develop',
    category: 'Implementation',
    summary: 'Implement approved task packets với scope fidelity, task-aware inspection, verification, review, và state sync.',
    when: ['Spec hoặc task packet đã approve.', 'Muốn implement một task an toàn.', 'Task có completion criteria và evidence expectations.'],
    flow: [['Load', 'Mở spec.json và chọn một unblocked task.'], ['Extract', 'Đọc scope, related files, requirements, contracts, evidence commands.'], ['Inspect', 'Scout entrypoints thật, callers, patterns, prior outputs, blast radius.'], ['Implement', 'Chỉ sửa active task boundary trừ khi có scope escape hợp lý.'], ['Gate', 'Chạy tests và review; fail thì quay lại implementation.'], ['Sync', 'Chỉ đóng task sau khi có proof.']],
    output: 'Production code reachable thật, kèm task evidence và synchronized state.',
    avoid: 'Không dùng trước spec approval hoặc để âm thầm thay named technology bằng placeholder.',
    next: '/hapo:test và /hapo:code-review',
  },
  test: {
    title: 'Test',
    command: '/hapo:test',
    category: 'Verification',
    summary: 'Chạy verification thật và trả verdict cụ thể, không xem command xanh bề mặt là proof.',
    when: ['Implementation đổi behavior.', 'Cần blast-radius, full-suite, spec-aware, hoặc UI verification.', 'Task cần evidence trước khi done.'],
    flow: [['Detect', 'Tìm test runner và commands liên quan.'], ['Scope', 'Chọn blast-radius, full-suite, spec-aware, hoặc UI mode.'], ['Execute', 'Chạy lint, type, build, test, hoặc UI checks thật.'], ['Compare', 'So kết quả với requirements, design contracts, evidence, reachability.'], ['Verdict', 'Trả PASS, FAIL, PARTIAL, hoặc NO_TESTS cùng next action.']],
    output: 'Test verdict có commands, outcomes, failures, coverage, và reachability notes khi cần.',
    avoid: 'Không bao giờ xem NO_TESTS, skipped tests, assertion bị làm yếu, hoặc zero executed tests là pass.',
    next: '/hapo:code-review',
  },
  'code-review': {
    title: 'Code Review',
    command: '/hapo:code-review',
    category: 'Review',
    summary: 'Review findings-first cho spec compliance, code quality, security, regressions, và contract drift.',
    when: ['Diff đã sẵn sàng để review.', 'Cần adversarial pass trước khi mark done.', 'PR, commit, path, hoặc feature scope cần risk analysis.'],
    flow: [['Target', 'Load pending diff, commit, PR, path, hoặc feature scope.'], ['Spec compliance', 'Bắt thiếu requirement, scope dư, runtime choice sai, claim chưa verify.'], ['Code quality', 'Review YAGNI, KISS, DRY, boundaries, naming, tests.'], ['Adversarial pass', 'Tìm security holes, races, edge cases, regressions.'], ['Score', 'Trả pass/fail với findings theo severity.']],
    output: 'Blocking review report. Critical findings chặn completion.',
    avoid: 'Không dùng như bước polish/tóm tắt. Review phải cố phá change.',
    next: '/hapo:sync sau khi fix và verification sạch',
  },
  sync: {
    title: 'Sync',
    command: '/hapo:sync',
    category: 'State',
    summary: 'Update task status, task_registry, task markdown, phase, và audit result để agent sau có thể tin project record.',
    when: ['Task status cần đổi sau proof.', 'spec.json và task markdown bị drift.', 'Cần phase advancement hoặc audit task registry và physical task files.'],
    flow: [['Resolve', 'Xác định feature, task reference, target status, phase, hoặc audit mode.'], ['Machine state', 'Update chính xác spec.json task_registry, task_files, phase, timestamps, blocker.'], ['Human state', 'Update task markdown status và checked criteria.'], ['Proof gate', 'Từ chối done nếu chưa có verification receipt.'], ['Audit', 'Repair mismatch giữa task_files, registry, và task files.']],
    output: 'spec.json, task_registry, và task markdown đã sync với status có proof.',
    avoid: 'Không mark done từ chat memory hoặc khi task file chưa có evidence.',
    next: 'Docs checkpoint hoặc next unblocked task',
  },
  debug: {
    title: 'Debug',
    command: '/hapo:debug',
    category: 'Diagnosis',
    summary: 'Workflow diagnosis-only cho bug, failing tests, CI issues, performance issues, và UI regressions.',
    when: ['Chưa biết root cause.', 'Test, build, CI job, UI flow, hoặc production behavior fail.', 'Cần evidence trước khi sửa code.'],
    flow: [['Scout', 'Map affected files, callers, runtime, config, tests, recent changes.'], ['Evidence', 'Capture exact symptom, command, logs, stack trace, environment facts.'], ['Patterns', 'So failing path với nearby working examples.'], ['Hypotheses', 'Test nhiều cause giả thuyết, từng biến một.'], ['Root cause', 'Trace file/line hoặc config source và giải thích why now.'], ['Plan', 'Định nghĩa blast radius và verification checks cho fix.']],
    output: 'Root-cause contract sẵn sàng cho `/hapo:hotfix` hoặc implementation work.',
    avoid: 'Không sửa product code trong lúc diagnosis, trừ temporary instrumentation đã remove trước handoff.',
    next: '/hapo:hotfix',
  },
  hotfix: {
    title: 'Hotfix',
    command: '/hapo:hotfix',
    category: 'Repair',
    summary: 'Repair hẹp, có evidence sau diagnosis. Fix cause mà không mở rộng scope.',
    when: ['Root cause đã xác định.', 'Fix nên nhỏ và an toàn.', 'Production bug cần targeted regression checks.'],
    flow: [['Evidence', 'Bắt đầu từ debug contract hoàn chỉnh hoặc diagnose trước.'], ['Scope', 'Giới hạn file set vào confirmed cause.'], ['Fix', 'Apply repair thật, không che symptom.'], ['Verify', 'Chạy lại reproduction và targeted regression checks.'], ['Report', 'Nêu cause, fix, evidence, residual risk, follow-up.']],
    output: 'Focused repair có before/after proof.',
    avoid: 'Không dùng cho broad redesign, speculative refactor, hoặc feature work.',
    next: '/hapo:test và /hapo:code-review',
  },
  docs: {
    title: 'Docs',
    command: '/hapo:docs',
    category: 'Documentation',
    summary: 'Tạo, refresh, summarize, hoặc reconstruct project documentation từ source code.',
    when: ['Docs thiếu hoặc stale.', 'Code change ảnh hưởng architecture, commands, deployment, onboarding.', 'Legacy system cần source-backed as-is documentation.'],
    flow: [['Mode', 'Chọn init, update, summarize, hoặc reconstruct.'], ['Scout', 'Đọc source, config, commands, architecture, docs root.'], ['Write', 'Update living docs hoặc build docs/as-is cho bounded scope.'], ['Uncertainty', 'Track assumptions, unknowns, evidence.'], ['Validate', 'Chạy docs validators trước handoff.']],
    output: 'Documentation bám current source behavior.',
    avoid: 'Không bịa architecture claim nếu không back được bằng files, commands, hoặc runtime evidence.',
    next: '/hapo:specs cho modernization work, hoặc release handoff',
  },
  inspect: {
    title: 'Inspect',
    command: '/hapo:inspect',
    category: 'Discovery',
    summary: 'Codebase discovery nhanh cho file finding, task context, entrypoints, call paths, và blast radius.',
    when: ['Relevant files chưa rõ.', 'Task chạm nhiều directories.', 'Debugging, implementation, hoặc review cần scoped context.'],
    flow: [['Scope gate', 'Tránh root-wide scans và no-scan paths.'], ['Structure scout', 'Map top-level layout cho broad scopes.'], ['Explore', 'Search focused sub-scopes song song hoặc targeted reads.'], ['Aggregate', 'Trả files, call paths, integration points, risks, next steps.']],
    output: 'Context map gọn để follow-up work an toàn hơn.',
    avoid: 'Không scan secrets, build outputs, node_modules, .git, hoặc cả repo khi bounded scope là đủ.',
    next: 'Skill nhỏ nhất phù hợp với task đã discover',
  },
  git: {
    title: 'Git',
    command: '/hapo:git',
    category: 'Release',
    summary: 'Branch, commit, push, PR, finish, và worktree operations an toàn với secret scanning và focused commits.',
    when: ['Verified changes sẵn sàng commit hoặc publish.', 'Cần focused conventional commit.', 'Parallel work cần isolated worktree.'],
    flow: [['Status', 'Inspect branch, staged diff, unstaged diff, intended action.'], ['Secret scan', 'Từ chối commit chứa keys, tokens, passwords, credentials.'], ['Split', 'Giữ commit focused và conventional khi cần.'], ['Publish', 'Commit, push, hoặc mở PR an toàn.'], ['Finish', 'Đưa lựa chọn merge, PR, keep, discard sau verification.']],
    output: 'Version-control history sạch, không leak secrets hoặc overwrite unrelated work.',
    avoid: 'Không force-push, delete worktrees, hoặc discard changes nếu chưa có xác nhận rõ.',
    next: 'Push, PR, hoặc branch finish flow',
  },
};
